# Name of loaded config, to show to user
name = "Block Device Manager (with FHI)"

# Modules to load in load environment
[[module]]
file = "bdm.irx"
env = ["LE"]
[[module]]
file = "iomanX.irx"
env = ["LE"]
[[module]]
file = "fileXio.irx"
env = ["LE"]

# Modules to load in emulation environment
[[module]]
file = "fhi_bd_defrag.irx"
func = "FHI_BD"
env = ["EE"]
